### PR TITLE
Add support for websocket transport

### PR DESCRIPTION
**Pull request by sgebauer**
libpebble2 can communicate with pebble via the pebble smartphone app (developer connection).
For me, this is the only way how i can use linux-remote because the bluetooth connection doesn't seem to work on Linux Mint 17.1.

### CODE REVIEW

**Comment by susundberg** [comment]
Hi!

Thanks for committing the patch! I merged it manually to the main branch with minor modifications.

Most importantly - i dropped your commit on the libpebble2+pip side, since i really want to ship stripped down version with the repository, so that one can avoid usage of pip if wanted [1]. I tried to clarify the reasoning and possibilities to readme.md

I'll keep this open still few days and close it after that if no futher actions are required.

[1] That is me - i prefer distribution python packages always, and use pip in very last resort. This way i think i keep my computer more 'clean'.

Cheers!
Pauli

**Comment by susundberg** [comment]
One more thing; i was testing out the 
`pebble.send_packet(AppRunState(command = 0x01, data=AppRunStateStart(uuid = uuid.UUID(settings.uuid))))` 

but at least with my configuration it seems to be dead line; if the watchapp is not running, the start-up will print some NACKS and then exit. Did it work for you? Did i expect wrong thing (that it would have launched the app)?

**Comment by sgebauer** [comment]
Yes, this line should launch the app. It works for me via websocket and via bluetooth.
(I got the bluetooth connection to work with the trick from #1 (opening the pebble's bluetooth settings). However, it only works once after pairing the pebble with the pc. Then I have to disconnect and pair the devices again.)

**Comment by susundberg** [comment]
Hi again!

I re-tried and was not able to get the watch to launch the app. How did you
install the pebble watch software? Via store or custom upload? I'll leave
the line there for now anyway.

About the BT-issues; At least ubuntu launches by default some ModemManager
that tries to steal the device -- do make sure that no other process is
accessing the device.

**Comment by sgebauer** [comment]
I installed the watch app via the official Pebble app. Do you use an "old" Pebble? Maybe the command only works on the new Timeline OS (SDK v3). If the line doesn't break anything, just leave it there ;)

About the BT issue: I don't have ModemManager installed. Is there a way to check if a process is accessing a bluetooth device? 'lsof | grep rfcomm0' doesn't print anything.

**Comment by susundberg** [comment]
Yeah, i have the "original" pebble in use. That truly might be the case, i did not see any comments about it though. And -- which is bit weird -- when i do upload a new binary for the watch the app starts there fine, so there might be something fishy with my installation. 

Anyway, the line stays there.

About the BT issue: i have been using the same method, just make sure you run it (lsof) with enough permissions (aka root). But not really another ideas -- i had severe problems with my ubuntu 14.04, but newer 15.04 worked out of the box .. I guess dmesg is not showing anything weird? And the BT works fine with some other device (= driver is good) ?

**Comment by susundberg** [comment]
Hi! I am closing this as its merged to master and the conversation went into BT-issue. I am sorry i cannot help too much on that side, but please do open a new issue / pull request if you find a way to get it working properly. A wiki update would be also nice if you have time : https://github.com/susundberg/pebble-linux-remote#testing--bug--support

**Pull request closed without merging**
